language: python
# services:
  # - go
  # - singularity
python:
  # - "2.7"
  # - "3.5"
  - "3.7"

# cache:
#   directories: 
#     - $HOME/.pip
#     # - $HOME/virtualenv ### too big
before_install: [] 
install:
  - echo pass
  - python -V
  - pip install pyinstaller
  - pip install .
script:
  - set -e
  #- make test.sh
  - pytest .
  - make build -B
  - bin/luck --help
  - bin/luckmake --help
  - bin/luckmake example-ece264-hw04.dir  
  # - python test.py --all
  # - ls -lhtr /deps/*
  # - tree /deps
